version: '3.5'

services:
  blueprint_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blueprint_nodejs
    image: blueprint_nodejs
    environment:
      DATABASE_NAME: "blueprint_nodejs"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
    volumes:
    - "./app:/src/app"
    ports:
      - "8080:8080"
  
  postgres_db:
    container_name: postgres_db
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: blueprint_nodejs
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always